#+title: Emacs configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Org file that makes an el file

Hello! This is an org-mode file that automatically generates an init.el file for emacs configuration. Cool, huh?

** Basic settings

These are some basic settings to make life a little better. They don't relate to packages or anything fancy like that.

#+begin_src emacs-lisp
  ;; command is a lot more ergonomic than option
  ;; also, less confusing when going back and forth between mac and windows
  (setq mac-command-modifier 'meta)

  ;; C-c h to open this file, my config
  (defun dkj/open-config ()
    "Open this file"
    (interactive)
    (push-mark)
    (find-file "~/.emacs.d/config.org"))
  (global-set-key (kbd "C-c h") 'dkj/open-config)
  ;; I can't see a god damn at this small font size
  (set-face-attribute 'default nil :height 160)
  ;; Turn off the beeping with visible-bell
  (setq visible-bell t)

  ;; Turn off all the bars
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  ;; Always prompt before exiting
  (setq confirm-kill-emacs 'yes-or-no-p)

  ;; isearch with regexp by default. Swap bindings with plain isearch
  (global-set-key (kbd "C-s") 'isearch-forward-regexp)
  (global-set-key (kbd "C-r") 'isearch-backward-regexp)
  (global-set-key (kbd "C-M-s") 'isearch-forward)
  (global-set-key (kbd "C-M-r") 'isearch-backward)

  ;; When I send mail from emacs, open the default mail client (because I haven't set up sending mail from emacs yet).
  (setq send-mail-function 'mailclient-send-it)
#+end_src

** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =dkj/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is in my .emacs.d directory and, if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp
  (defun dkj/org-babel-tangle-config ()
    "Automatically tangle our config.org config file when we save it"
    (when (string-equal (file-name-directory (buffer-file-name))
			(expand-file-name user-emacs-directory))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
	(org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'dkj/org-babel-tangle-config)))
#+end_src

** Using packages

Packages are hip and cool and emacs is pretty good at using them.

#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

*** Automatic Package Updates

The auto-package-update package helps us keep our Emacs packages up to date!  It will prompt you after a certain number of days either at startup or at a specific time of day to remind you to update your packages.

You can also use =M-x auto-package-update-now= to update right now!

#+begin_src emacs-lisp
  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))
#+end_src

** Use the modus-vivendi theme - https://protesilaos.com/emacs/modus-themes

#+begin_src emacs-lisp
  (use-package modus-themes) ;; package is needed before Emacs 28
  (require 'modus-themes)
  (modus-themes-load-themes)
  (modus-themes-load-vivendi)
#+end_src

** Org mode stuff

Org-mode is cool. That's an understatement, org-mode is one of the main reasons to use Emacs.

*** org-mode general settings

#+begin_src emacs-lisp
  (setq org-directory "~/Documents/org/")
  (setq org-agenda-files '("~/Documents/org/"))
  (setq org-id-locations-file "~/Documents/org/.org-id-locations")
  (setq org-startup-truncated nil)
#+end_src

*** Markdown export

Markdown is still useful, so we need a backend to export to it.

#+begin_src emacs-lisp
  (setq org-export-backends '(ascii html icalendar latex md odt))
#+end_src

*** Org execute other languages inline

With C-c C-c

#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (python . t)
     ))

  (setq org-babel-python-command "python3")
#+end_src

** Which-key

=which-key= is a package which describes available key bindings interactively. If you use a binding which prefixes other bindings and then wait, it will pop up a small buffer with the available follow ups.

#+begin_src emacs-lisp
  (use-package which-key)
  (require 'which-key)
  (which-key-mode)
#+end_src

** Magit

Magit is a git frontend. People really like it. I'm used to fugitive. Anyway, this is Emacs, so we use Magit.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

** Markdown support

In emacs we want to mostly write [[Org mode stuff][org-mode]] when it comes to markup languages. Still, markdown is useful.

#+begin_src emacs-lisp
  (use-package markdown-mode)
#+end_src
